### ISSUE TITLE
Status and comparison to Feathers JS?

### ISSUE THREAD

**Issue by brodybits** [usehenri/henri#25]
I found Feathers JS through the issue you raised at https://github.com/zeit/next.js/issues/469. Then you started this project. I am just curious what the status is and how it compares to Feathers? I wonder if this should be documented?

**Comment by reel** [comment]
Glad you are raising an issue. It used to be built upon feathers but I decided to add a rails-like autoloader.

This framework loads your models & controllers and enables next and next (react or vue) with SSR.

I am building two projects on this so, it will change a bit on the database side as it's hard to integrate a flow... I was amazed by interoperability of the database fw we use but it is limited alot 

Looking to support mongoose and a SQL orm and limit interoperability.

Your thoughts?

**Comment by reel** [comment]
Feathers will deliver an API driven experience. They rock at this. This framework will provide a rails like experience with fast code reloading (both server side and client side)... We barely just bring the right tools together to enhance your development experience
